MyCompany/MyCompany/Models/ViewComponents/SidebarViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public SidebarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult) View("Default", dataManager.ServiceItems.GetAll()));
        }
    }
}

MyCompany/MyCompany/Controllers/ControlPanelController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyCompany.Controllers
{
    public class ControlPanelController : Controller
    {
        public IActionResult Index() => View();
    }
}

MyCompany/MyCompany/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Domain.Repositories.MongoDb;

namespace MyCompany.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager _dataManager;

        public HomeController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(_dataManager.TextFields.Get("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(_dataManager.TextFields.Get("PageContacts"));
        }
    }
}

MyCompany/MyCompany/Controllers/NewsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MyCompany.Controllers
{
    public class NewsController : Controller
    {
        private readonly DataManager _dataManager;
        private readonly IWebHostEnvironment _hostingEnv;

        public NewsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            _dataManager = dataManager;
            _hostingEnv = hostingEnvironment;
        }
        public IActionResult Index(string id)
        {
            if (id != default)
            {
                return View("Show", _dataManager.NewsItems.Get(id));
            }

            ViewBag.TextField = _dataManager.TextFields.Get("PageNews");
            return View(_dataManager.NewsItems.GetAll());
        }

        public IActionResult AllNews()
        {
            return View(_dataManager.NewsItems.GetAll());
        }
        public IActionResult Edit(string id)
        {
            var entity = id == default ? new NewsItem() : _dataManager.NewsItems.Get(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(NewsItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    var newName = Guid.NewGuid().ToString() + Path.GetExtension(titleImageFile.FileName);
                    model.TitleImagePath = newName;
                    using (var stream = new FileStream(Path.Combine(_hostingEnv.WebRootPath, "images/news", newName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                if (model.Id == null)
                    _dataManager.NewsItems.Create(model);
                else
                    _dataManager.NewsItems.Update(model.Id, model);
                return RedirectToAction(nameof(NewsController.AllNews), nameof(NewsController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            _dataManager.ServiceItems.Delete(id);
            return RedirectToAction(nameof(NewsController.AllNews), nameof(NewsController).CutController());
        }
    }
}

MyCompany/MyCompany/Controllers/ServicesController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager _dataManager;
        private readonly IWebHostEnvironment _hostingEnv;

        public ServicesController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            _dataManager = dataManager;
            _hostingEnv = hostingEnvironment;
        }

        public IActionResult Index(string id)
        {
            if (id != default)
            {
                return View("Show", _dataManager.ServiceItems.Get(id));
            }

            ViewBag.TextField = _dataManager.TextFields.Get("PageServices");
            return View(_dataManager.ServiceItems.GetAll());
        }

        public IActionResult AllServices()
        {
            return View(_dataManager.ServiceItems.GetAll());
        }
        public IActionResult Edit(string id)
        {
            var entity = id == default ? new ServiceItem() : _dataManager.ServiceItems.Get(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    var newName = Guid.NewGuid().ToString() + Path.GetExtension(titleImageFile.FileName);
                    model.TitleImagePath = newName;
                    using (var stream = new FileStream(Path.Combine(_hostingEnv.WebRootPath, "images/service", newName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                if (model.Id == null)
                    _dataManager.ServiceItems.Create(model);
                else
                    _dataManager.ServiceItems.Update(model.Id, model);
                return RedirectToAction(nameof(ServicesController.AllServices), nameof(ServicesController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            _dataManager.ServiceItems.Delete(id);
            return RedirectToAction(nameof(ServicesController.AllServices), nameof(ServicesController).CutController());
        }
    }
}

MyCompany/MyCompany/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;
using System.Collections.Generic;

namespace MyCompany.Controllers
{
    public class TextFieldsController : Controller
    {
        private readonly DataManager _dataManager;

        public TextFieldsController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult Fields() => View(_dataManager.TextFields.GetAll());

        public IActionResult Edit(string codeWord)
        {
            var entity = _dataManager.TextFields.Get(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                _dataManager.TextFields.Update(model.Id, model);
                return RedirectToAction(nameof(TextFieldsController.Fields), nameof(TextFieldsController).CutController());
            }
            return View(model);
        }
    }
}

MyCompany/MyCompany/Views/ControlPanel/Index.cshtml
@{ 
    ViewBag.Title = "Панель управления";
}


<div>
    <style type="text/css">
        a {
            display:block;
            padding: 10px 0;
        }
    </style>
        <a asp-controller="News" asp-action="AllNews"> Редактирование новостей</a >
        <a asp-controller="Services" asp-action="AllServices"> Редактирование услуг</a >
        <a asp-controller="TextFields" asp-action="Fields"> Редактирование страниц</a >
    
</div>

MyCompany/MyCompany/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.Title;
}

@Html.Raw(Model.Text)

MyCompany/MyCompany/Views/Home/Index.cshtml
@model TextField
@{
    ViewBag.Title = Model.Title;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

MyCompany/MyCompany/Views/News/AllNews.cshtml
@model List<NewsItem>
@{

}
<div>
    <h2>Редактирование новостей</h2>
    <div>
        <h3>Новости:</h3>
        <div class="div-box">
            <a asp-controller="News" asp-action="Edit" asp-route-id="">Добавить новость</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (NewsItem entity in Model)
                {
                    <div style="border: 3px dashed #61a7f2; border-radius: 5px; padding:20px 0; margin-bottom:10px">
                        Название услуги:
                        <a asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                        <br>Действие:
                        <a asp-controller="News" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>
                        <form style="display: inline-block; padding: 20px;" id="form-@entity.Id" asp-controller="News" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a style="color:darkred" href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
                        </form>
                    </div>
                }
            </div>
        }
        else
        {
            <p>Новости еще не добавлены</p>
        }
    </div>
</div>

MyCompany/MyCompany/Views/News/Edit.cshtml
@model NewsItem
@{
    string strTitle = "Редактировать новость";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-controller="News" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/MyCompany/Views/News/Index.cshtml
@model List<NewsItem>
@{
    TextField textField = ViewBag.TextField;
    ViewBag.Title = textField.Title;
}
<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (NewsItem entity in Model)
            {
            <li>
                <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                    <img src="~/images/news/@entity.TitleImagePath" alt="" class="left" />
                </a>
                <h4>@entity.Title</h4>
                @if (entity.Text.Length > 280)
                    entity.Text = entity.Text.Substring(0, 280) + "...</p>";
                @Html.Raw(entity.Text)
            </li>
            }
        </ul>
        <div style="text-align:center">
            @Html.Raw(textField.Text)
        </div>
    }
    else
    {
        <p>Новости не найдены</p>
    }
</div>

MyCompany/MyCompany/Views/News/Show.cshtml
@model NewsItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <div>
        <img class="img-block" src="~/images/news/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>

MyCompany/MyCompany/Views/Services/AllServices.cshtml
@model List<ServiceItem>
@{

}
<div>
    <h2>Редактирование услуг</h2>
    <div>
        <h3>Услуги:</h3>
        <div class="div-box">
            <a asp-controller="Services" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                <div style="border: 3px dashed #61a7f2; border-radius: 5px; padding:20px 0; margin-bottom:10px">
                    Название услуги:
                    <a asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        @($"{entity.Title}")
                    </a>
                    <br>Действие:
                    <a asp-controller="Services" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>
                    <form style="display: inline-block; padding: 20px;" id="form-@entity.Id" asp-controller="Services" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@entity.Id">
                        <a style="color:darkred" href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
                    </form>
                </div>
                }
            </div>
        }
        else
            {
                <p>Услуги еще не добавлены</p>
            }
    </div>
</div>

MyCompany/MyCompany/Views/Services/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form  asp-controller="Services" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/MyCompany/Views/Services/Index.cshtml
@model List<ServiceItem>
@{
    TextField textField = ViewBag.TextField;
    ViewBag.Title = textField.Title;
}
<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/service/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
        <div style="text-align:center">
            @Html.Raw(textField.Text)
        </div>
    }
    else
    {
        <p>Услуги найдены</p>
    }
</div>

MyCompany/MyCompany/Views/Services/Show.cshtml
@model ServiceItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="~/images/service/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>

MyCompany/MyCompany/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<ServiceItem>

@if (Model?.Any() == true)
{
    <section>
        <h2>Наши услуги</h2>
        <ul class="small-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>
                        @entity.Title
                    </h4>
                    <p>
                        @entity.Subtitle
                    </p>
                </li>
            }
        </ul>
    </section>
}

MyCompany/MyCompany/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true" />

MyCompany/MyCompany/Views/Shared/FooterPartial.cshtml
<!-- Footer -->
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div id="copyright">
                    &copy; @Config.CompanyName. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
                </div>

            </div>
        </div>
    </div>
</div>

MyCompany/MyCompany/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.CompanyName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="News" asp-action="Index">Новости</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Услуги</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        <a asp-area="" asp-controller="ControlPanel" asp-action="Index">Панель управления</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

MyCompany/MyCompany/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

MyCompany/MyCompany/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

MyCompany/MyCompany/Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">

</div>

MyCompany/MyCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                    @await Html.PartialAsync("SidebarPartial")
                </div>
            </div>
        </div>
        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>

MyCompany/MyCompany/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/MyCompany/Views/TextFields/Fields.cshtml
@model List<TextField>    

<div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        @foreach(var textField in Model)
            {
                <a style="display: block; padding: 10px 0;" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="@textField.CodeWord">@textField.Title</a>
            }
    </div>